# -*- coding: utf-8 -*-
"""3dmath.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11lrExu94-BArxXdiXk1Gi6ifdDxTqwBU
"""

!pip install streamlit plotly numpy sympy

import streamlit as st
import numpy as np
import plotly.graph_objects as go
import sympy as sp
from sympy.parsing.sympy_parser import parse_expr, standard_transformations, implicit_multiplication_application

# 設定網頁標題
st.set_page_config(page_title="3D 數學函數繪圖器", layout="wide")
st.title("📐 3D 數學函數繪圖器")
st.markdown("請在下方輸入包含 `x` 和 `y` 的數學函數，系統將自動產生可轉動的 3D 曲面圖！")
st.markdown("> **範例**: `sin(sqrt(x**2 + y**2))` 或 `x**2 - y**2` 或 `cos(x) * sin(y)`")

# 側邊欄：參數設定
with st.sidebar:
    st.header("⚙️ 參數設定")
    func_str = st.text_input("輸入函數 f(x, y):", value="sin(sqrt(x**2 + y**2))")

    st.subheader("座標軸範圍")
    x_min, x_max = st.slider("X 軸範圍", -20.0, 20.0, (-10.0, 10.0))
    y_min, y_max = st.slider("Y 軸範圍", -20.0, 20.0, (-10.0, 10.0))

    st.subheader("網格解析度")
    resolution = st.slider("解析度 (越大越精細，但運算較久)", 10, 150, 50)

# 主要繪圖區
try:
    # 1. 安全地解析數學函數 (使用 sympy)
    x, y = sp.symbols('x y')
    # 加入轉換規則，允許隱式乘法 (例如把 2x 視為 2*x)
    transformations = standard_transformations + (implicit_multiplication_application,)
    expr = parse_expr(func_str, transformations=transformations)

    # 2. 將 sympy 表示式轉換為 numpy 函式以加速計算
    f = sp.lambdify((x, y), expr, "numpy")

    # 3. 產生 X, Y 網格資料
    x_vals = np.linspace(x_min, x_max, resolution)
    y_vals = np.linspace(y_min, y_max, resolution)
    X, Y = np.meshgrid(x_vals, y_vals)

    # 4. 計算 Z 值
    Z = f(X, Y)

    # 處理常數函數的情況 (例如輸入 '5')
    if np.isscalar(Z):
        Z = np.full_like(X, Z)
    # 處理單變數函數的情況 (例如只輸入 'x**2')
    elif Z.shape != X.shape:
        Z = np.broadcast_to(Z, X.shape)

    # 5. 使用 Plotly 繪製可轉動的 3D 曲面圖
    fig = go.Figure(data=[go.Surface(z=Z, x=X, y=Y, colorscale='Viridis')])

    fig.update_layout(
        title=f"<b>f(x, y) = {func_str}</b>",
        autosize=True,
        height=700,
        margin=dict(l=0, r=0, b=0, t=50),
        scene=dict(
            xaxis_title='X 軸',
            yaxis_title='Y 軸',
            zaxis_title='Z 軸'
        )
    )

    # 在 Streamlit 中顯示 Plotly 圖表
    st.plotly_chart(fig, use_container_width=True)

except Exception as e:
    st.error("⚠️ 函數解析錯誤或計算失敗！請檢查數學函數的語法是否正確 (例如：乘號 `*` 是否遺漏、括號是否對稱)。")
    st.warning(f"詳細錯誤訊息: {e}")